# Минимальная конфигурация сервера
version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:6.2.7'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    env_file:
      - .env
  olgram:
    image: ghcr.io/civsocit/olgram/bot:stable
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - olgram-cert:/cert
    ports:
      - "${WEBHOOK_PORT}:80"
    depends_on:
      - postgres
      - redis

volumes:
  database:
  redis-db:
  olgram-cert:
